# ./docker-compose.yml
version: "3.9"

services:
  app:
    build: .
    container_name: spim_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      PHP_MEMORY_LIMIT: 512M
      XDEBUG_MODE: ""               # or: "debug,develop"
      XDEBUG_CONFIG: "client_host=host.docker.internal idekey=SPIM"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
      - redis

  web:
    image: nginx:1.27-alpine
    container_name: spim_web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./ops/nginx/spim.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: spim_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: spim
      MYSQL_USER: spim
      MYSQL_PASSWORD: spim
      MYSQL_ROOT_PASSWORD: spim
    ports:
      - "3306:3306"
    volumes:
      - spim_mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: spim_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  spim_mysql_data:
